aquasecurity/starboard-lens-extension

.github/workflows/build.yaml

chore: Name GitHub Actions workflow

---

package.json
renderer.tsx

Update to Lens 4.0.0-beta.4 & add sub-menus

---

README.md
package-lock.json
renderer.tsx
src/ciskubebench-reports-store.ts
src/components/configaudit-reports-list.tsx
src/components/vulnerabilities-list.tsx
src/components/vulnerability-report-details.tsx
src/components/vulnerability-reports-list.tsx
src/components/workload-vulnerabilities.tsx
src/configaudit-reports-store.ts
src/vulnerability-report.ts
src/vulnerability-reports-store.ts

feat: Display VulnerabilityReports in workload details pane

---

package-lock.json
package.json

chore: Bump up Lens API to v4.0.0-rc.1

---

.github/workflows/build.yaml
.github/workflows/release.yaml
package-lock.json
package.json

chore: Add release workflow

---

package-lock.json
package.json
src/components/vulnerabilities-list.tsx
src/components/vulnerability-report-details.tsx
src/vulnerability-report.ts

Adding necessary changes to unlock `virtual` feature of Lens `Table` component. With current API, key things are:
- Any item passed into VirtualList should have `getId()` & `getName()` methods
- `TableRow` should have `sortItem` prop
- Special styling should be added (height) explicitly for `Table` instance with `virtual` feature enabled. Made with `emotion` library. (You can learn more about styling extensions here https://docs.k8slens.dev/v4.0.0-rc.1/extensions/capabilities/styling/)
Also, expanded Vulnerability List area a bit for better readability.

Using virtual table for Vulnerabilities list

---

package-lock.json
package.json

release: Prepare v0.0.1-alpha.2

---

package-lock.json
package.json
src/components/vulnerability-report-details.tsx
src/vulnerability-report.ts

fix: Display image digest in VulnerabilityReport details component

---

.github/workflows/release.yaml
package-lock.json
package.json

chore: Refine release workflow

---

.github/workflows/release.yaml
README.md
src/components/ciskubebench-reports-list.tsx
src/components/configaudit-reports-list.tsx
src/components/vulnerability-reports-list.tsx
src/components/workload-configaudit.tsx
src/components/workload-vulnerabilities.tsx

fix: Do not loadAll() in componentDidMount callback

---

package-lock.json
package.json
src/components/vulnerabilities-list.tsx

feat: Order vulnerabilities by severity

---

package-lock.json

fix: Vulnerability warning in the init package

---

src/components/configaudit-report-details.tsx
src/components/configaudit-reports-list.tsx
src/configaudit-report.ts

feat: Add pass count to ConfigAuditReport components

---

package-lock.json
package.json

release: Prepare v0.0.2

---

README.md

docs: Add compatibility matrix

---

package-lock.json
package.json
src/components/ciskubebench-report-details.scss
src/components/ciskubebench-report-details.tsx
src/components/configaudit-report-details.scss
src/components/configaudit-report-details.tsx
src/components/vulnerability-report-details.scss
src/components/vulnerability-report-details.tsx
webpack.config.js

feat: Use Badge components to render report summaries

---

renderer.tsx
src/components/ciskubebench-report-details.tsx
src/components/configaudit-report-details.tsx
src/components/configaudit-reports-list.tsx
src/components/vulnerability-report-details.tsx
src/configaudit-report.ts
src/configaudit-reports-store.ts

feat: Add ClusterConfigAuditReport

---

package-lock.json
package.json
src/configauditreports/types.ts

refactor: simplify ConfigAuditReport types definition

---

package-lock.json
package.json
src/ciskubebenchreports/cisresults-list.scss
src/ciskubebenchreports/cisresults-list.tsx
src/ciskubebenchreports/cissections-list.tsx
src/ciskubebenchreports/details.tsx
src/configauditreports/checks-list.tsx
src/vulnerabilityreports/list.tsx

fix: show all CIS benchmark sections

---

src/ciskubebenchreports/cisresults-list.scss
src/vulnerabilityreports/list.scss
src/vulnerabilityreports/list.tsx
src/vulnerabilityreports/types.ts

feat: use primaryLink to render vulnerability reports

---

package-lock.json
package.json
src/configauditreports/checks-list.tsx
src/configauditreports/types.ts

feat(configaudit): display description or message

---

src/ciskubebenchreports/page.tsx
src/configauditreports/page.tsx
src/vulnerabilityreports/page.tsx

feat: position scanner column as last one

---

src/configauditreports/checks-list.scss

feat: extend severity column in configuration audit checks list

---

package-lock.json
package.json

release: prepare v0.11.0

---

package-lock.json
package.json

release: prepare v0.12.0
